name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - hlky
          - lstein
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3
      # better caching?
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain  
      - uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'docker-compose.yml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
