name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - sygil
          - invoke
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3
      # better caching?
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain
