name: Build Images

on:
  push:
    branches: master
  pull_request:
      paths:
        - docker-compose.yml
        - services

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    strategy:
      matrix:
        profile:
          - dummy
          #- auto
          # - hlky
          #- lstein
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - run: docker compose --profile ${{ matrix.profile }} build --progress plain 
      - run: docker inspect 
      
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'docker-compose.yml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
